apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: asw-project
  labels:
    app: instagnam
    service: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagnam
      service: postgres
  template:
    metadata:
      labels:
        app: instagnam
        service: postgres
    spec:
      containers:
      - name: asw-postgres
        image: postgres:12.3
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
