apiVersion: v1
kind: Service
metadata:
  name: ricette-seguite-service
  namespace: asw-project
spec:
  type: ClusterIP
  selector:
    app: ricette-seguite
  ports:
  - port: 8080
    targetPort: 8080
  
