apiVersion: v1
kind: Service
metadata:
  name: ricette-seguite-service
  namespace: asw-project
spec:
  type: NodePort
  selector:
    app: ricette-seguite
  ports:
  - name: web-interface
    protocol: TCP
    nodePort: 30300
    port: 8080
    targetPort: 8080
  - name: remote-java-api
    protocol: TCP
    nodePort: 30400
    port: 50051
    targetPort: 50051
