apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: asw-project
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
  - name: web-interface
    protocol: TCP
    nodePort: 31100
    port: 8080
    targetPort: 8080
  - name: remote-java-api
    protocol: TCP
    nodePort: 31200
    port: 50054
    targetPort: 50054
