apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-ricette-deployment
  namespace: asw-project
  labels:
    app: instagnam
    service: postgres-ricette
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagnam
      service: postgres-ricette
  template:
    metadata:
      labels:
        app: instagnam
        service: postgres-ricette
    spec:
      containers:
      - name: asw-postgres-ricette
        image: postgres:12.3
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-ricette-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdb-ricette
      volumes:
        - name: postgresdb-ricette
          persistentVolumeClaim:
            claimName: postgres-ricette-pv-claim
